### ISSUE TITLE
Xiaomi 4 Pro

### ISSUE THREAD

**Issue by im-tesla** [dnandha/stlink-lks32#1]
Hi! Thank you very much for that, do you think it is possible with 4 pro too?

**Comment by encryptize** [comment]
For 4Pro 1st gen you can use https://github.com/dnandha/m365-rescue

If you mean 4Pro 2nd gen, there is nothing available for it now.

**Comment by im-tesla** [comment]
> For 4Pro 1st gen you can use https://github.com/dnandha/m365-rescue
> 
> 
> 
> If you mean 4Pro 2nd gen, there is nothing available for it now.

Okay thank you very much
